# Generated by Django 3.2.8 on 2021-10-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_provider', models.CharField(max_length=45)),
                ('pro_existences', models.IntegerField()),
                ('pro_date', models.DateField()),
                ('pro_description', models.CharField(max_length=255)),
                ('pro_category', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
